### ISSUE TITLE
Building on MacOS

### ISSUE THREAD

**Issue by yetzt** [flohoff/addressextract#2]
Could you please make cmake look for the header files in `/usr/local/lib` as well, so it builds nicely on MacOS with homebrew? The dependencies are easy enough to install:

`brew install cmake boost spatialindex gdal expat nlohmann-json`

**Comment by flohoff** [comment]
Hi,
i added {CMAKE_SYSROOT}/usr/local/include to the nlohmann search path. Hope that helps?

**Comment by yetzt** [comment]
thanks for answering :)

meanwhile homebrew uses `/opt/homebrew/lib` and `/opt/homebrew/include`.
`nlohmann-json` is found, but not `spatialindex` although it's present in `/opt/homebrew/include/spatialindex`

```
-- Checking for module 'spatialindex'
--   No package 'spatialindex' found
```

but it compiles without problems anyway.

**Comment by flohoff** [comment]
Ah - okay - forgot spatialindex - pushed another change

**Comment by yetzt** [comment]
it appears to be found, if i add `message("spatialindex directory ${LSI_INCLUDE_DIRS}")` to the `CMakeLists.txt` it shows `spatialindex directory /opt/homebrew/include/spatialindex` 
it was just confusing since the output from `pkg_check_modules(LSI spatialindex)` indicates otherwise

it builds fine on macos with homebrew, 

``` sh
brew install cmake boost spatialindex gdal expat nlohmann-json

git clone https://github.com/flohoff/addressextract.git

cd addressextract

git clone https://github.com/mapbox/protozero
git clone https://github.com/osmcode/libosmium

cmake .
make

```

in case you want to add it to the readme. 

thanks for your effort!
